# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

#---------------------------#

# Site settings
title: Renata Rapyo
description: >-
  Brazil based Marketer, Game & System Designer, currently creating mobile free-to-play games
baseurl: ""
url: "http://rapyo.me"
permalink: /:title:output_ext

email: renata.rapyo@gmail.com
linkedin: https://www.linkedin.com/in/renatarapyo/

# CMS settings
prose:
  media: "assets/images"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - README_image_example.png
